In [47]:
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from tensorflow.keras.utils import to_categorical
from matplotlib import pyplot
import numpy as np 

In [48]:
def data_normalize(data_temp):
    data_temp2=data_temp.T
    data_temp2 -=np.mean(data_temp2,axis=0)
    data_temp2 /=np.std(data_temp2,axis=0)
    data_temp=data_temp2.T
    return data_temp

In [49]:
def load_file(filepath):
	dataframe = read_csv(filepath, header=None, delim_whitespace=True)
	return dataframe.values

In [50]:
def load_group(filenames, prefix=''):
	loaded = list()
	for name in filenames:
		data = load_file(prefix + name)
		loaded.append(data)
	# stack group so that features are the 3rd dimension
	loaded = dstack(loaded)
	return loaded

In [60]:
import pathlib
def load_dataset_group(group, prefix=''):
    filepathData = prefix + group +'/data/'
    filepathLabel = prefix + group +'/label/'
    # load all 9 files as a single array
    filenames = list()
    # body acceleration
    fileNamesX = []
    fileNamesY = []
    #fileNamesTrain.append(12)
    if (group == "train"):
        for x in range(1022):
            fileNamesX.append(str(x+1)+'.txt')
        for x in range(1022):
            fileNamesY.append(str(x+1)+'_label.txt')
    if (group == "test"):
        for y in range(332):
            fileNamesX.append(str(y+1)+'.txt')
        for y in range(332):
            fileNamesY.append(str(y+1)+'_label.txt')

    #filenames += ["acc_x1.txt","acc_x2.txt","acc_y1.txt","acc_y2.txt","acc_z1.txt","acc_z2.txt"]
    #print(filenames)
    # body gyroscope
    #filenames += ["gyr_x1.txt","gyr_x2.txt","gyr_y1.txt","gyr_y2.txt","gyr_z1.txt","gyr_z2.txt"]
    # load input data
    X = load_group(fileNamesX, filepathData)
    # load class output
    y = load_group(fileNamesY, filepathLabel)
    return X, y

In [61]:
def load_dataset(prefix=''):
	# load all train
	trainX, trainy = load_dataset_group('train', prefix + 'Dataset_8/')
	print(trainX.shape, trainy.shape)
	# load all test
	testX, testy = load_dataset_group('test', prefix + 'Dataset_8/')
	print(testX.shape, testy.shape)
	# zero-offset class values
	trainy = trainy - 1
	testy = testy - 1
	# one hot encode y
	trainy = to_categorical(trainy)
	testy = to_categorical(testy)
	print(trainX.shape, trainy.shape, testX.shape, testy.shape)
	return trainX, trainy, testX, testy

In [62]:
trainX, trainy, testX, testy=load_dataset()

(1024, 6, 1022) (1024, 1, 1022)
(1024, 6, 332) (1024, 1, 332)
(1024, 6, 1022) (1024, 1, 1022, 1) (1024, 6, 332) (1024, 1, 332, 1)


In [63]:
trainX.transpose(0,2,1)

array([[[ 5.94531e+00,  4.35938e+00,  7.28516e+00,  2.75635e-01,
          7.26320e-02,  3.69629e-01],
        [-1.00547e+01,  1.76856e+00,  7.14844e+00, -6.59668e-01,
          1.71289e+00,  3.09375e+00],
        [-8.13281e+00,  9.64844e-01,  8.73535e-01,  2.32617e+00,
          1.87988e-01, -1.40918e+00],
        ...,
        [ 1.51269e+00, -9.45313e+00, -1.65723e+00,  5.44922e-01,
         -3.71338e-01,  2.81070e-02],
        [-1.80078e+00, -1.24219e+01,  6.55078e+00, -1.21680e+00,
          5.36133e-01,  5.37410e-02],
        [ 3.24609e+00, -8.72656e+00, -1.62842e-01,  9.06738e-01,
         -8.93066e-01,  1.90552e-01]],

       [[ 5.84766e+00,  4.39844e+00,  7.22656e+00,  1.97144e-01,
          1.09314e-01,  3.19336e-01],
        [-1.00781e+01,  2.14063e+00,  6.81641e+00, -6.48926e-01,
          1.99512e+00,  2.90039e+00],
        [-7.25391e+00,  1.20019e+00,  5.00977e-01,  2.56641e+00,
          3.38623e-01, -1.42578e+00],
        ...,
        [ 1.12988e+00, -9.53906e+00, -1.82910

In [64]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('trainX.npy', trainX)
#np.load(tranx.npy)

In [65]:
# load numpy array from npy file
from numpy import load
# load array
trainX = load('trainX.npy')
# print the array
print(trainX)

[[[ 5.94531e+00 -1.00547e+01 -8.13281e+00 ...  1.51269e+00 -1.80078e+00
    3.24609e+00]
  [ 4.35938e+00  1.76856e+00  9.64844e-01 ... -9.45313e+00 -1.24219e+01
   -8.72656e+00]
  [ 7.28516e+00  7.14844e+00  8.73535e-01 ... -1.65723e+00  6.55078e+00
   -1.62842e-01]
  [ 2.75635e-01 -6.59668e-01  2.32617e+00 ...  5.44922e-01 -1.21680e+00
    9.06738e-01]
  [ 7.26320e-02  1.71289e+00  1.87988e-01 ... -3.71338e-01  5.36133e-01
   -8.93066e-01]
  [ 3.69629e-01  3.09375e+00 -1.40918e+00 ...  2.81070e-02  5.37410e-02
    1.90552e-01]]

 [[ 5.84766e+00 -1.00781e+01 -7.25391e+00 ...  1.12988e+00 -6.22559e-01
    3.49609e+00]
  [ 4.39844e+00  2.14063e+00  1.20019e+00 ... -9.53906e+00 -1.28984e+01
   -1.02031e+01]
  [ 7.22656e+00  6.81641e+00  5.00977e-01 ... -1.82910e+00 -6.85547e+00
   -9.19434e-01]
  [ 1.97144e-01 -6.48926e-01  2.56641e+00 ...  4.92432e-01 -3.33203e+00
    1.02539e+00]
  [ 1.09314e-01  1.99512e+00  3.38623e-01 ... -4.17725e-01  4.52344e+00
   -5.03418e-01]
  [ 3.19336e-01  2.

In [66]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('trainy.npy', trainy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
trainy = load('trainy.npy')
# print the array
print(trainy)

[[[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 ...


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]]


In [67]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testX.npy', testX)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testX = load('testX.npy')
# print the array
print(testX)

[[[ 1.34746e+01  9.30866e+00 -2.71024e+00 ...  6.16746e+00 -2.48997e-01
    6.23690e-01]
  [ 3.62003e+00  6.12916e-01  1.22583e+00 ... -5.44920e+00  2.09972e+00
   -2.32238e-01]
  [ 1.54187e+00  6.60800e-01  1.01227e+01 ...  5.38217e+00  1.01502e+01
   -7.77517e+00]
  [ 6.96386e-01 -3.42084e-02  0.00000e+00 ...  2.48011e-01  0.00000e+00
   -1.16309e+00]
  [ 3.62854e-01  2.44346e-02  0.00000e+00 ...  1.06291e-01  0.00000e+00
   -6.43852e-01]
  [ 2.56563e-02  8.55210e-03  0.00000e+00 ... -6.71952e-02  0.00000e+00
    1.22170e-03]]

 [[ 1.44131e+01  9.02135e+00 -2.71024e+00 ...  6.37815e+00 -2.37026e-01
    1.47483e+00]
  [ 1.77171e+00  4.59687e-01  1.22583e+00 ... -8.63828e+00  2.34392e+00
   -5.41090e-01]
  [-3.25611e-01  6.79953e-01  1.01227e+01 ...  4.91290e+00  1.01670e+01
   -4.48314e+00]
  [ 5.18014e-01 -5.37562e-02  0.00000e+00 ...  5.97426e-01  3.29867e-02
   -8.11229e-01]
  [-7.33038e-02  9.16298e-02  0.00000e+00 ...  5.04575e-01 -9.77380e-03
   -7.83129e-01]
  [-9.77384e-02 -1.

In [68]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testy.npy', testy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testy = load('testy.npy')
# print the array
print(testy)

[[[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 ...


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]]
