In [3]:
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from tensorflow.keras.utils import to_categorical
from matplotlib import pyplot
import numpy as np 

In [4]:
def data_normalize(data_temp):
    data_temp2=data_temp.T
    data_temp2 -=np.mean(data_temp2,axis=0)
    data_temp2 /=np.std(data_temp2,axis=0)
    data_temp=data_temp2.T
    return data_temp

In [5]:
def load_file(filepath):
	dataframe = read_csv(filepath, header=None, delim_whitespace=True)
	return dataframe.values

In [6]:
def load_group(filenames, prefix=''):
	loaded = list()
	for name in filenames:
		data = load_file(prefix + name)
		loaded.append(data)
	# stack group so that features are the 3rd dimension
	loaded = dstack(loaded)
	return loaded

In [13]:
def load_dataset_group(group, prefix=''):
	filepath = prefix + group + '/data/'
	# load all 9 files as a single array
	filenames = list()
	# body acceleration
	filenames += ["acc_x1.txt","acc_x2.txt","acc_y1.txt","acc_y2.txt","acc_z1.txt","acc_z2.txt"]
	# body gyroscope
	filenames += ["gyr_x1.txt","gyr_x2.txt","gyr_y1.txt","gyr_y2.txt","gyr_z1.txt","gyr_z2.txt"]
	# load input data
	X = load_group(filenames, filepath)
	# load class output
	y = load_file(prefix + group + '/y_'+group+'.txt')
	return X, y

In [14]:
def load_dataset(prefix=''):
	# load all train
	trainX, trainy = load_dataset_group('train', prefix + 'Dataset_6/')
	print(trainX.shape, trainy.shape)
	# load all test
	testX, testy = load_dataset_group('test', prefix + 'Dataset_6/')
	print(testX.shape, testy.shape)
	# zero-offset class values
	trainy = trainy - 1
	testy = testy - 1
	# one hot encode y
	trainy = to_categorical(trainy)
	testy = to_categorical(testy)
	print(trainX.shape, trainy.shape, testX.shape, testy.shape)
	return trainX, trainy, testX, testy

In [15]:
trainX, trainy, testX, testy=load_dataset()

(66542, 128, 12) (66542, 1)
(7600, 128, 12) (7600, 1)
(66542, 128, 12) (66542, 2) (7600, 128, 12) (7600, 2)


In [19]:
trainX.transpose(0,2,1)

array([[[-1.29670e+01, -1.29670e+01, -1.30334e+01, ..., -6.71162e+00,
         -6.97326e+00, -7.22548e+00],
        [-1.20189e+01, -1.20919e+01, -1.16355e+01, ..., -1.15188e+01,
         -1.18238e+01, -1.20771e+01],
        [-3.69665e+00, -3.91579e+00, -3.67540e+00, ..., -3.42565e+00,
         -3.13910e+00, -3.10191e+00],
        ...,
        [ 6.84170e-02,  3.11540e-02, -1.71810e-02, ...,  6.75390e-02,
          4.84900e-03,  2.92450e-02],
        [-5.86430e-02, -9.72040e-02,  2.88060e-02, ..., -2.85618e-01,
         -1.33837e-01, -6.21170e-02],
        [-1.08734e-01,  9.73760e-02,  2.85770e-01, ...,  2.61140e-02,
         -2.67630e-02, -1.30000e-01]],

       [[-8.45632e+00, -8.46425e+00, -6.61817e+00, ..., -3.69784e+00,
         -2.93828e+00, -1.74657e+00],
        [-1.33596e+01, -1.33508e+01, -1.22107e+01, ..., -1.15888e+01,
         -1.24926e+01, -1.39729e+01],
        [ 2.91518e+01,  2.30292e+01,  1.57440e+01, ...,  1.81570e+00,
          3.47339e+00,  7.46856e+00],
        ...,


In [24]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('trainX.npy', trainX)
#np.load(tranx.npy)

In [25]:
# load numpy array from npy file
from numpy import load
# load array
trainX = load('trainX.npy')
# print the array
print(trainX)

[[[-1.29670e+01 -1.20189e+01 -3.69665e+00 ...  6.84170e-02 -5.86430e-02
   -1.08734e-01]
  [-1.29670e+01 -1.20919e+01 -3.91579e+00 ...  3.11540e-02 -9.72040e-02
    9.73760e-02]
  [-1.30334e+01 -1.16355e+01 -3.67540e+00 ... -1.71810e-02  2.88060e-02
    2.85770e-01]
  ...
  [-6.71162e+00 -1.15188e+01 -3.42565e+00 ...  6.75390e-02 -2.85618e-01
    2.61140e-02]
  [-6.97326e+00 -1.18238e+01 -3.13910e+00 ...  4.84900e-03 -1.33837e-01
   -2.67630e-02]
  [-7.22548e+00 -1.20771e+01 -3.10191e+00 ...  2.92450e-02 -6.21170e-02
   -1.30000e-01]]

 [[-8.45632e+00 -1.33596e+01  2.91518e+01 ...  2.07694e-01 -1.52716e-01
    1.77151e-01]
  [-8.46425e+00 -1.33508e+01  2.30292e+01 ... -1.06539e-01 -2.05327e-01
    3.41588e-01]
  [-6.61817e+00 -1.22107e+01  1.57440e+01 ... -3.88816e-01 -1.71348e-01
    2.25638e-01]
  ...
  [-3.69784e+00 -1.15888e+01  1.81570e+00 ... -3.92670e-02  2.12638e-01
   -7.31100e-03]
  [-2.93828e+00 -1.24926e+01  3.47339e+00 ...  8.10160e-02  8.62850e-02
   -2.30678e-01]
  [-1.7

In [27]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('trainy.npy', trainy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
trainy = load('trainy.npy')
# print the array
print(trainy)

[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [28]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testX.npy', testX)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testX = load('testX.npy')
# print the array
print(testX)

[[[-1.44118e+01 -1.29800e+01  2.43575e+00 ... -1.19116e+00  3.19489e-01
    4.98047e-01]
  [-1.50393e+01 -1.32974e+01  2.17832e+00 ... -9.23126e-01  2.04483e-01
    1.84987e-01]
  [-1.26261e+01 -1.35871e+01  9.53400e-01 ... -3.09074e-01  8.73260e-02
   -6.22190e-02]
  ...
  [-8.82997e+00 -1.01643e+01 -1.67984e+00 ...  5.59160e-02 -1.94497e-01
   -2.04676e-01]
  [-9.45147e+00 -1.03102e+01 -1.04685e+00 ... -2.41877e-01 -2.10715e-01
   -3.68658e-01]
  [-1.02787e+01 -1.11034e+01  1.49411e-01 ... -1.01720e-02 -1.23954e-01
   -2.53706e-01]]

 [[ 2.96559e+00 -1.45099e+01 -1.52162e+01 ... -2.15372e+00  8.58310e-02
    1.10169e-01]
  [ 3.73388e+00 -1.47704e+01 -1.35460e+01 ... -1.06442e+00 -6.39100e-02
    1.19383e-01]
  [ 4.98484e+00 -1.41372e+01 -1.27584e+01 ... -7.70520e-02 -3.44060e-01
    4.21920e-02]
  ...
  [ 8.54343e+00 -1.12547e+01 -3.26453e+00 ... -4.97700e-03 -6.67421e-01
   -4.78220e-02]
  [ 8.43463e+00 -1.16046e+01 -3.66124e+00 ... -3.54218e-01 -1.09092e+00
   -6.84500e-03]
  [ 6.0

In [29]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testy.npy', testy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testy = load('testy.npy')
# print the array
print(testy)

[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]
