In [1]:
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from tensorflow.keras.utils import to_categorical
from matplotlib import pyplot
import numpy as np 

In [2]:
def data_normalize(data_temp):
    data_temp2=data_temp.T
    data_temp2 -=np.mean(data_temp2,axis=0)
    data_temp2 /=np.std(data_temp2,axis=0)
    data_temp=data_temp2.T
    return data_temp

In [3]:
def load_file(filepath):
    dataframe = read_csv(filepath, header=None, delim_whitespace=True)
    return dataframe.values

In [4]:
def load_group(filenames, prefix=''):
    loaded = list()
    for name in filenames:
        data = load_file(prefix + name)
        loaded.append(data)
    # stack group so that features are the 3rd dimension
    loaded = dstack(loaded)
    return loaded

In [5]:
def load_dataset_group(group, prefix=''):
    filepath = prefix + group + '/Inertial_Signals/'
    # load all 9 files as a single array
    filenames = list()
    # body acceleration
    filenames += ["acc_x.txt","acc_y.txt","acc_z.txt"]
    # body gyroscope
    filenames += ["gyr_x.txt","gyr_y.txt","gyr_z.txt"]
    # load input data
    X = load_group(filenames, filepath)
    # load class output
    y = load_file(prefix + group + '/y_'+group+'.txt')
    return X, y

In [6]:
def load_dataset(prefix=''):
    # load all train
    trainX, trainy = load_dataset_group('train', prefix + 'Dataset_3/')
    print(trainX.shape, trainy.shape)
    # load all test
    testX, testy = load_dataset_group('test', prefix + 'Dataset_3/')
    print(testX.shape, testy.shape)
    # zero-offset class values
    trainy = trainy - 1
    testy = testy - 1
    # one hot encode y
    trainy = to_categorical(trainy)
    testy = to_categorical(testy)
    print(trainX.shape, trainy.shape, testX.shape, testy.shape)
    return trainX, trainy, testX, testy

In [7]:
trainX, trainy, testX, testy=load_dataset()

(26283, 128, 6) (26283, 1)
(2991, 128, 6) (2991, 1)
(26283, 128, 6) (26283, 118) (2991, 128, 6) (2991, 118)


In [8]:
trainX.transpose(0,2,1)

array([[[-7.38372e+00, -7.65187e+00, -7.87214e+00, ..., -1.32735e+01,
         -1.27180e+01, -1.19040e+01],
        [-2.85389e+00, -3.27527e+00, -3.56257e+00, ..., -4.17549e+00,
         -4.98952e+00, -4.89375e+00],
        [-3.06458e-01, -9.48104e-01, -2.13563e+00, ..., -2.03028e+00,
         -1.79086e+00, -1.44610e+00],
        [-6.23083e-02, -1.24617e-01, -1.33169e-01, ...,  1.03847e-01,
          5.86431e-02, -1.93033e-01],
        [ 2.19912e-01, -7.08604e-02, -3.22537e-01, ...,  3.29867e-01,
          1.85703e-01,  3.33532e-01],
        [-4.27606e-02, -1.09956e-02,  0.00000e+00, ...,  6.71952e-02,
          5.74213e-02,  2.68781e-02]],

       [[-1.09774e+00, -1.36470e+00, -1.25217e+00, ..., -5.97353e-01,
          9.09797e-01,  3.86065e+00],
        [ 7.80629e+00,  7.91763e+00,  7.64708e+00, ...,  1.16945e+01,
          1.47315e+01,  1.64805e+01],
        [-4.03184e+00, -3.34350e+00, -4.00071e+00, ..., -6.63553e+00,
         -5.99508e+00, -4.87579e+00],
        [-1.83260e-01, -9.

In [9]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('trainX.npy', trainX)
#np.load(tranx.npy)

In [10]:
# load numpy array from npy file
from numpy import load
# load array
trainX = load('trainX.npy')
# print the array
print(trainX)

[[[-7.38372e+00 -2.85389e+00 -3.06458e-01 -6.23083e-02  2.19912e-01
   -4.27606e-02]
  [-7.65187e+00 -3.27527e+00 -9.48104e-01 -1.24617e-01 -7.08604e-02
   -1.09956e-02]
  [-7.87214e+00 -3.56257e+00 -2.13563e+00 -1.33169e-01 -3.22537e-01
    0.00000e+00]
  ...
  [-1.32735e+01 -4.17549e+00 -2.03028e+00  1.03847e-01  3.29867e-01
    6.71952e-02]
  [-1.27180e+01 -4.98952e+00 -1.79086e+00  5.86431e-02  1.85703e-01
    5.74213e-02]
  [-1.19040e+01 -4.89375e+00 -1.44610e+00 -1.93033e-01  3.33532e-01
    2.68781e-02]]

 [[-1.09774e+00  7.80629e+00 -4.03184e+00 -1.83260e-01  1.70798e+00
    2.22355e-01]
  [-1.36470e+00  7.91763e+00 -3.34350e+00 -9.68832e-01  7.91681e-01
   -1.71042e-02]
  [-1.25217e+00  7.64708e+00 -4.00071e+00 -2.55342e-01 -3.92176e-01
   -1.34390e-01]
  ...
  [-5.97353e-01  1.16945e+01 -6.63553e+00 -8.18560e-02  3.68963e-01
   -8.42994e-02]
  [ 9.09797e-01  1.47315e+01 -5.99508e+00  1.25838e-01  1.06291e-01
   -2.44346e-02]
  [ 3.86065e+00  1.64805e+01 -4.87579e+00  7.50143e

In [11]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testX.npy', testX)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testX = load('testX.npy')
# print the array
print(testX)

[[[-8.44674e+00 -1.50643e+01 -6.35900e+00  5.74213e-02  1.02503e+00
    6.51182e-01]
  [-1.83875e+00 -1.13102e+01 -3.05500e+00  3.65298e-01  4.63036e-01
   -5.10684e-01]
  [ 3.39977e+00 -7.10599e+00  8.61913e-01  5.25344e-01  2.07694e-01
   -8.38107e-01]
  ...
  [ 9.09797e-01 -1.14347e+01 -8.57124e+00 -2.79776e-01  1.31580e+00
   -1.33169e-01]
  [ 6.78038e+00 -1.29000e+01 -5.22894e+00  4.78918e-01  2.10138e-01
   -5.10683e-01]
  [ 8.11155e+00 -1.67307e+01 -2.40378e+00 -3.66520e-03 -1.53449e+00
   -3.75071e-01]]

 [[ 2.76770e+00 -8.19775e+00  5.17148e-01  4.38601e-01 -6.16974e-01
    3.40863e-01]
  [ 2.67193e+00 -5.55455e+00 -2.20267e-01  2.24798e-01 -6.59735e-02
    3.81180e-01]
  [ 3.75411e+00 -4.61602e+00 -5.93762e-01  9.77384e-02  2.90772e-01
    1.29503e-01]
  ...
  [ 9.26077e+00 -9.11712e+00 -5.17148e-01 -1.85703e-01 -3.29867e-01
    3.45750e-01]
  [ 9.26077e+00 -9.11712e+00 -5.17148e-01  2.79776e-01 -3.42085e-02
    6.10870e-03]
  [ 9.05966e+00 -6.50265e+00  5.74608e-02  4.10501e

In [12]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testy.npy', testy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testy = load('testy.npy')
# print the array
print(testy)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
