In [2]:
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from tensorflow.keras.utils import to_categorical
from matplotlib import pyplot
 
    # save numpy array as npy file
from numpy import asarray
from numpy import save
from numpy import load


In [3]:
def load_file(filepath):
	dataframe = read_csv(filepath, header=None, delim_whitespace=True)
	return dataframe.values

In [4]:
def load_group(filenames, prefix=''):
	loaded = list()
	for name in filenames:
		data = load_file(prefix + name)
		loaded.append(data)
	# stack group so that features are the 3rd dimension
	loaded = dstack(loaded)
	return loaded

In [5]:
def load_dataset_group(group, prefix=''):
	filepath = prefix + group + '/Inertial/'
	# load all 9 files as a single array
	filenames = list()
	# body acceleration
	filenames += ["acc_x.txt", "acc_y.txt", "acc_z.txt"]
	# body gyroscope
	filenames += ["gyr_x.txt", "gyr_y.txt", "gyr_z.txt"]
	# load input data
	X = load_group(filenames, filepath)
	# load class output
	y = load_file(prefix + group + '/y_'+group+'.txt')
	return X, y

In [6]:
def load_dataset(prefix=''):
	# load all train
	trainX, trainy = load_dataset_group('train', prefix + 'Dataset_2/')
	print(trainX.shape, trainy.shape)
	# load all test
	testX, testy = load_dataset_group('test', prefix + 'Dataset_2/')
	print(testX.shape, testy.shape)
	# zero-offset class values
	trainy = trainy - 1
	testy = testy - 1
	# one hot encode y
	trainy = to_categorical(trainy)
	testy = to_categorical(testy)
	print(trainX.shape, trainy.shape, testX.shape, testy.shape)
	return trainX, trainy, testX, testy

In [7]:
trainX, trainy, testX, testy=load_dataset()

(44339, 128, 6) (44339, 1)
(4936, 128, 6) (4936, 1)
(44339, 128, 6) (44339, 20) (4936, 128, 6) (4936, 20)


In [8]:
trainX.transpose(0,2,1)

array([[[ 3.93008e+00,  9.42118e-01,  9.20571e-01, ...,  2.27449e+00,
          2.12246e+00,  2.03148e+00],
        [ 1.96803e+01,  1.82941e+01,  1.46310e+01, ...,  1.30963e+01,
          1.27324e+01,  1.31681e+01],
        [ 2.58574e-01, -1.89980e+00, -5.43484e-01, ...,  3.78643e+00,
          3.31118e+00,  1.90578e+00],
        [ 2.24431e+00, -1.85013e+00, -8.25717e-01, ..., -6.00133e-01,
         -2.28209e-01, -2.75588e-02],
        [ 6.18077e+00,  4.63309e-01, -3.28159e+00, ...,  9.42865e-01,
         -1.12641e-01,  1.21688e-01],
        [ 1.37462e+00, -1.45415e+00,  4.57932e-01, ..., -3.56070e-01,
         -5.46304e-01, -1.31911e+00]],

       [[-6.21535e+00, -2.25960e+00, -4.47416e-01, ..., -2.26207e+00,
         -1.18438e+00,  3.29143e+00],
        [-1.96085e+01, -1.37988e+01, -4.13778e+00, ..., -5.11611e-01,
          3.78164e+00, -5.52162e-02],
        [-1.81816e+01, -8.46844e+00, -1.17316e+00, ...,  1.70280e+00,
          3.20688e+00,  3.54342e-01],
        [-2.09221e+00, -1.

In [9]:
# define data
# save to npy file
save('trainX.npy', trainX)
#np.load(tranx.npy)

In [10]:
# load array
trainX = load('trainX.npy')
# print the array
print(trainX)

[[[ 3.93008e+00  1.96803e+01  2.58574e-01  2.24431e+00  6.18077e+00
    1.37462e+00]
  [ 9.42118e-01  1.82941e+01 -1.89980e+00 -1.85013e+00  4.63309e-01
   -1.45415e+00]
  [ 9.20571e-01  1.46310e+01 -5.43484e-01 -8.25717e-01 -3.28159e+00
    4.57932e-01]
  ...
  [ 2.27449e+00  1.30963e+01  3.78643e+00 -6.00133e-01  9.42865e-01
   -3.56070e-01]
  [ 2.12246e+00  1.27324e+01  3.31118e+00 -2.28209e-01 -1.12641e-01
   -5.46304e-01]
  [ 2.03148e+00  1.31681e+01  1.90578e+00 -2.75588e-02  1.21688e-01
   -1.31911e+00]]

 [[-6.21535e+00 -1.96085e+01 -1.81816e+01 -2.09221e+00  9.41954e-01
   -1.56992e-01]
  [-2.25960e+00 -1.37988e+01 -8.46844e+00 -1.75601e+00  6.61643e-02
    6.70692e-01]
  [-4.47416e-01 -4.13778e+00 -1.17316e+00 -1.65804e+00 -1.18599e+00
    6.40263e-01]
  ...
  [-2.26207e+00 -5.11611e-01  1.70280e+00 -1.60165e+00  1.40633e+00
    3.36281e-01]
  [-1.18438e+00  3.78164e+00  3.20688e+00  1.52732e+00  2.13520e+00
   -2.59541e-01]
  [ 3.29143e+00 -5.52162e-02  3.54342e-01  4.17290e

In [33]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testX.npy', testX)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testX = load('testX.npy')
# print the array
print(testX)

[[[ 2.53666e+00 -1.59933e+01 -3.92266e+01 -1.54250e+00 -4.91300e+00
   -3.51537e-01]
  [ 4.65414e+00 -2.09487e+01 -2.12340e+01 -1.42763e+00 -1.50686e+00
   -2.96327e-01]
  [ 2.49596e+00 -1.93636e+01 -5.88592e+00 -1.95509e-01  3.55619e+00
   -2.31096e-01]
  ...
  [ 3.14905e+00 -5.86665e+00  1.25969e+00  4.88224e-01  7.49763e-02
    3.36723e-02]
  [ 3.49419e+00 -6.89351e+00  7.49086e-01  4.81583e-01  3.68066e-01
    2.07943e-01]
  [ 4.54128e+00 -8.50974e+00 -1.08700e+00  6.16846e-01  3.64054e-01
    1.45092e-01]]

 [[-6.85819e+00 -2.49667e+01 -1.75256e+01 -1.26447e+00 -1.20481e+00
    5.32632e-01]
  [-3.06619e+00 -2.11356e+01 -1.22480e+01 -2.46933e-01  3.70903e-01
   -7.82179e-01]
  [-1.17608e+00 -1.48205e+01 -1.01156e+01  4.70814e-01  5.90606e-01
   -6.31069e-01]
  ...
  [-3.93584e-01 -3.50272e+00 -4.35098e+00  8.65519e-01 -1.96699e-01
    1.36221e-01]
  [-1.05659e+00 -5.65039e+00 -6.57193e+00  1.14200e-01 -2.89153e-01
    1.85739e-01]
  [-2.08812e+00 -9.21618e+00 -8.90000e+00 -8.74166e

In [34]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testy.npy', testy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testy = load('testy.npy')
# print the array
print(testy)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
