In [110]:
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from tensorflow.keras.utils import to_categorical
from matplotlib import pyplot
 
    # save numpy array as npy file
from numpy import asarray
from numpy import save
from numpy import load


In [111]:
def data_normalize(data_temp):
    data_temp2=data_temp.T
    data_temp2 -=np.mean(data_temp2,axis=0)
    data_temp2 /=np.std(data_temp2,axis=0)
    data_temp=data_temp2.T
    return data_temp

In [112]:
def load_file(filepath):
	dataframe = read_csv(filepath, header=None, delim_whitespace=True)
	return dataframe.values

In [113]:
def load_group(filenames, prefix=''):
	loaded = list()
	for name in filenames:
		data = load_file(prefix + name)
		loaded.append(data)
	# stack group so that features are the 3rd dimension
	loaded = dstack(loaded)
	return loaded

In [114]:
def load_dataset_group(group, prefix=''):
	filepath = prefix + group + '/Inertial/'
	# load all 9 files as a single array
	filenames = list()
	# body acceleration
	filenames += ["acc_x.txt", "acc_y.txt", "acc_z.txt"]
	# body gyroscope
	filenames += ["gyr_x.txt", "gyr_y.txt", "gyr_z.txt"]
	# load input data
	X = load_group(filenames, filepath)
	# load class output
	y = load_file(prefix + group + '/y_'+group+'.txt')
	return X, y

In [115]:
def load_dataset(prefix=''):
	# load all train
	trainX, trainy = load_dataset_group('train', prefix + 'Dataset_2/')
	print(trainX.shape, trainy.shape)
	# load all test
	testX, testy = load_dataset_group('test', prefix + 'Dataset_2/')
	print(testX.shape, testy.shape)
	# zero-offset class values
	trainy = trainy - 1
	testy = testy - 1
	# one hot encode y
	trainy = to_categorical(trainy)
	testy = to_categorical(testy)
	print(trainX.shape, trainy.shape, testX.shape, testy.shape)
	return trainX, trainy, testX, testy

In [116]:
trainX, trainy, testX, testy=load_dataset()

(44339, 128, 6) (44339, 1)
(4936, 128, 6) (4936, 1)
(44339, 128, 6) (44339, 20) (4936, 128, 6) (4936, 20)


In [117]:
trainX.transpose(0,2,1)

array([[[ 3.93008e+00,  9.42118e-01,  9.20571e-01, ...,  2.27449e+00,
          2.12246e+00,  2.03148e+00],
        [ 1.96803e+01,  1.82941e+01,  1.46310e+01, ...,  1.30963e+01,
          1.27324e+01,  1.31681e+01],
        [ 2.58574e-01, -1.89980e+00, -5.43484e-01, ...,  3.78643e+00,
          3.31118e+00,  1.90578e+00],
        [ 2.24431e+00, -1.85013e+00, -8.25717e-01, ..., -6.00133e-01,
         -2.28209e-01, -2.75588e-02],
        [ 6.18077e+00,  4.63309e-01, -3.28159e+00, ...,  9.42865e-01,
         -1.12641e-01,  1.21688e-01],
        [ 1.37462e+00, -1.45415e+00,  4.57932e-01, ..., -3.56070e-01,
         -5.46304e-01, -1.31911e+00]],

       [[-6.21535e+00, -2.25960e+00, -4.47416e-01, ..., -2.26207e+00,
         -1.18438e+00,  3.29143e+00],
        [-1.96085e+01, -1.37988e+01, -4.13778e+00, ..., -5.11611e-01,
          3.78164e+00, -5.52162e-02],
        [-1.81816e+01, -8.46844e+00, -1.17316e+00, ...,  1.70280e+00,
          3.20688e+00,  3.54342e-01],
        [-2.09221e+00, -1.

In [118]:
# define data
# save to npy file
save('trainX.npy', trainX)
#np.load(tranx.npy)
# load array
trainX = load('trainX.npy')
# print the array
print(trainX)

[[[ 3.93008e+00  1.96803e+01  2.58574e-01  2.24431e+00  6.18077e+00
    1.37462e+00]
  [ 9.42118e-01  1.82941e+01 -1.89980e+00 -1.85013e+00  4.63309e-01
   -1.45415e+00]
  [ 9.20571e-01  1.46310e+01 -5.43484e-01 -8.25717e-01 -3.28159e+00
    4.57932e-01]
  ...
  [ 2.27449e+00  1.30963e+01  3.78643e+00 -6.00133e-01  9.42865e-01
   -3.56070e-01]
  [ 2.12246e+00  1.27324e+01  3.31118e+00 -2.28209e-01 -1.12641e-01
   -5.46304e-01]
  [ 2.03148e+00  1.31681e+01  1.90578e+00 -2.75588e-02  1.21688e-01
   -1.31911e+00]]

 [[-6.21535e+00 -1.96085e+01 -1.81816e+01 -2.09221e+00  9.41954e-01
   -1.56992e-01]
  [-2.25960e+00 -1.37988e+01 -8.46844e+00 -1.75601e+00  6.61643e-02
    6.70692e-01]
  [-4.47416e-01 -4.13778e+00 -1.17316e+00 -1.65804e+00 -1.18599e+00
    6.40263e-01]
  ...
  [-2.26207e+00 -5.11611e-01  1.70280e+00 -1.60165e+00  1.40633e+00
    3.36281e-01]
  [-1.18438e+00  3.78164e+00  3.20688e+00  1.52732e+00  2.13520e+00
   -2.59541e-01]
  [ 3.29143e+00 -5.52162e-02  3.54342e-01  4.17290e

In [119]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testX.npy', testX)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testX = load('testX.npy')
# print the array
print(testX)

[[[ 2.53666e+00 -1.59933e+01 -3.92266e+01 -1.54250e+00 -4.91300e+00
   -3.51537e-01]
  [ 4.65414e+00 -2.09487e+01 -2.12340e+01 -1.42763e+00 -1.50686e+00
   -2.96327e-01]
  [ 2.49596e+00 -1.93636e+01 -5.88592e+00 -1.95509e-01  3.55619e+00
   -2.31096e-01]
  ...
  [ 3.14905e+00 -5.86665e+00  1.25969e+00  4.88224e-01  7.49763e-02
    3.36723e-02]
  [ 3.49419e+00 -6.89351e+00  7.49086e-01  4.81583e-01  3.68066e-01
    2.07943e-01]
  [ 4.54128e+00 -8.50974e+00 -1.08700e+00  6.16846e-01  3.64054e-01
    1.45092e-01]]

 [[-6.85819e+00 -2.49667e+01 -1.75256e+01 -1.26447e+00 -1.20481e+00
    5.32632e-01]
  [-3.06619e+00 -2.11356e+01 -1.22480e+01 -2.46933e-01  3.70903e-01
   -7.82179e-01]
  [-1.17608e+00 -1.48205e+01 -1.01156e+01  4.70814e-01  5.90606e-01
   -6.31069e-01]
  ...
  [-3.93584e-01 -3.50272e+00 -4.35098e+00  8.65519e-01 -1.96699e-01
    1.36221e-01]
  [-1.05659e+00 -5.65039e+00 -6.57193e+00  1.14200e-01 -2.89153e-01
    1.85739e-01]
  [-2.08812e+00 -9.21618e+00 -8.90000e+00 -8.74166e

In [120]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('trainy.npy', trainy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
trainy = load('trainy.npy')
# print the array
print(trainy)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [121]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# define data
#data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to npy file
save('testy.npy', testy)
#np.load(tranx.npy)
# load numpy array from npy file
from numpy import load
# load array
testy = load('testy.npy')
# print the array
print(testy)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [122]:
 data_normalize(trainX)

array([[[-0.25589738,  2.14123019, -0.81468756, -0.51246559,
          0.08664965, -0.64482932],
        [-0.20506804,  2.20934468, -0.600502  , -0.59359075,
         -0.27169112, -0.53849277],
        [-0.16623494,  2.17725158, -0.4164819 , -0.46472322,
         -0.88449895, -0.24531257],
        ...,
        [-0.19583188,  2.11736926,  0.12735078, -0.81029298,
         -0.48047156, -0.75812363],
        [-0.16385302,  2.13159927,  0.09332563, -0.67241844,
         -0.64741539, -0.74123804],
        [-0.12696936,  2.17129929, -0.15291012, -0.551894  ,
         -0.52109388, -0.81843193]],

       [[ 0.16039074, -1.44657465, -1.27536931,  0.65510209,
          1.0191536 ,  0.88729753],
        [ 0.38452954, -1.83619995, -0.81036734,  0.48144589,
          0.83212498,  0.94846688],
        [ 0.60465191, -1.93215371,  0.10576577, -0.22754724,
          0.09694625,  1.35233701],
        ...,
        [-1.44317161, -0.24425712,  1.27242474, -0.99084047,
          1.06936819,  0.33647627],
  

In [123]:
 data_normalize(testX)

array([[[ 0.86694215, -0.42319457, -2.04079836,  0.58293322,
          0.34826429,  0.66585326],
        [ 1.10934004, -1.3717763 , -1.39942412,  0.51996875,
          0.51229074,  0.6296009 ],
        [ 0.73998227, -2.06507162, -0.33559405,  0.39460864,
          0.87603269,  0.39004206],
        ...,
        [ 1.188583  , -2.06600311,  0.50654114,  0.2280489 ,
          0.07887022,  0.06395985],
        [ 1.18614632, -2.09112591,  0.32007846,  0.23568247,
          0.19986837,  0.14935029],
        [ 1.32568339, -2.00397083, -0.11023704,  0.32445833,
          0.25996453,  0.20410163]],

       [[ 0.17770272, -1.72677478, -0.94419203,  0.76599595,
          0.77227041,  0.95499772],
        [ 0.39318332, -1.8850415 , -0.76447636,  0.74864048,
          0.82653839,  0.68115567],
        [ 0.51929962, -1.76324835, -0.97617496,  0.79480525,
          0.81484502,  0.61047343],
        ...,
        [ 0.4331591 , -1.1572598 , -1.59117093,  1.07722909,
          0.53387185,  0.70417069],
  

In [125]:
save('trainX.npy', trainX)
save('testX.npy', testX)